# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/guilh/code/ipOverTelegram

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/guilh/code/ipOverTelegram

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/guilh/code/ipOverTelegram/CMakeFiles /mnt/c/Users/guilh/code/ipOverTelegram/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/guilh/code/ipOverTelegram/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named ipOverTelegram

# Build rule for target.
ipOverTelegram: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ipOverTelegram
.PHONY : ipOverTelegram

# fast build rule for target.
ipOverTelegram/fast:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/build
.PHONY : ipOverTelegram/fast

client.o: client.c.o

.PHONY : client.o

# target to build an object file
client.c.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.c.o
.PHONY : client.c.o

client.i: client.c.i

.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s

.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.c.s
.PHONY : client.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

server.o: server.c.o

.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i

.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s

.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.s
.PHONY : server.c.s

src/encryptor.o: src/encryptor.c.o

.PHONY : src/encryptor.o

# target to build an object file
src/encryptor.c.o:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/encryptor.c.o
.PHONY : src/encryptor.c.o

src/encryptor.i: src/encryptor.c.i

.PHONY : src/encryptor.i

# target to preprocess a source file
src/encryptor.c.i:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/encryptor.c.i
.PHONY : src/encryptor.c.i

src/encryptor.s: src/encryptor.c.s

.PHONY : src/encryptor.s

# target to generate assembly for a file
src/encryptor.c.s:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/encryptor.c.s
.PHONY : src/encryptor.c.s

src/request.o: src/request.c.o

.PHONY : src/request.o

# target to build an object file
src/request.c.o:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/request.c.o
.PHONY : src/request.c.o

src/request.i: src/request.c.i

.PHONY : src/request.i

# target to preprocess a source file
src/request.c.i:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/request.c.i
.PHONY : src/request.c.i

src/request.s: src/request.c.s

.PHONY : src/request.s

# target to generate assembly for a file
src/request.c.s:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/request.c.s
.PHONY : src/request.c.s

src/telegram.o: src/telegram.c.o

.PHONY : src/telegram.o

# target to build an object file
src/telegram.c.o:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/telegram.c.o
.PHONY : src/telegram.c.o

src/telegram.i: src/telegram.c.i

.PHONY : src/telegram.i

# target to preprocess a source file
src/telegram.c.i:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/telegram.c.i
.PHONY : src/telegram.c.i

src/telegram.s: src/telegram.c.s

.PHONY : src/telegram.s

# target to generate assembly for a file
src/telegram.c.s:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/telegram.c.s
.PHONY : src/telegram.c.s

src/tunnel.o: src/tunnel.c.o

.PHONY : src/tunnel.o

# target to build an object file
src/tunnel.c.o:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/tunnel.c.o
.PHONY : src/tunnel.c.o

src/tunnel.i: src/tunnel.c.i

.PHONY : src/tunnel.i

# target to preprocess a source file
src/tunnel.c.i:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/tunnel.c.i
.PHONY : src/tunnel.c.i

src/tunnel.s: src/tunnel.c.s

.PHONY : src/tunnel.s

# target to generate assembly for a file
src/tunnel.c.s:
	$(MAKE) -f CMakeFiles/ipOverTelegram.dir/build.make CMakeFiles/ipOverTelegram.dir/src/tunnel.c.s
.PHONY : src/tunnel.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... server"
	@echo "... client"
	@echo "... main"
	@echo "... ipOverTelegram"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... src/encryptor.o"
	@echo "... src/encryptor.i"
	@echo "... src/encryptor.s"
	@echo "... src/request.o"
	@echo "... src/request.i"
	@echo "... src/request.s"
	@echo "... src/telegram.o"
	@echo "... src/telegram.i"
	@echo "... src/telegram.s"
	@echo "... src/tunnel.o"
	@echo "... src/tunnel.i"
	@echo "... src/tunnel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

