#ifndef ENCRYPTOR_H_
#define ENCRYPTOR_H_

/**
 * Encryptor module.
 * 
 * Defines interfaces for functions and constants that encrypt and convert
 * byte data to natural language.
 * 
*/

#define VOCABULARY_LEN 256 // number of possible bytes (char)

// using byte to encode a char (1 byte of information)
typedef char byte;

/**
 * Encrypt bytes.
 * 
 * @param bytes: array of bytes to be encoded;
 * @param length: length of the array of bytes to be encoded;
 * @param destination: the pointer to the destination message location;
 * 
 * @return -1 for error,1 for completed execution
*/
int encrypt(const byte* bytes, const int length, char** destination);


/**
 * Decrypt message.
 * 
 * @param input: the input message pointer to be decrypted.
 * @param length: length of the iput message to be decrypted;
 * @param output: pointer to the bytes array to save the message;
 * 
 * @return: the size of the output or -1 in case of error;
*/
int decrypt(const char* input, const int length, byte** output);


/**
 * _dictionary
 * 
 * used by the interfaces to encode and decode the bytes in natural language.
*/
const char* _dictionary [VOCABULARY_LEN] = {
    "the",
    "of",
    "to",
    "and",
    "a",
    "in",
    "is",
    "it",
    "you",
    "that",
    "he",
    "was",
    "for",
    "on",
    "are",
    "with",
    "as",
    "I",
    "his",
    "they",
    "be",
    "at",
    "one",
    "have",
    "this",
    "from",
    "or",
    "had",
    "by",
    "hot",
    "word",
    "but",
    "what",
    "some",
    "we",
    "can",
    "out",
    "other",
    "were",
    "all",
    "there",
    "when",
    "up",
    "use",
    "your",
    "how",
    "said",
    "an",
    "each",
    "she",
    "which",
    "do",
    "their",
    "time",
    "if",
    "will",
    "way",
    "about",
    "many",
    "then",
    "them",
    "write",
    "would",
    "like",
    "so",
    "these",
    "her",
    "long",
    "make",
    "thing",
    "see",
    "him",
    "two",
    "has",
    "look",
    "more",
    "day",
    "could",
    "go",
    "come",
    "did",
    "number",
    "sound",
    "no",
    "most",
    "people",
    "my",
    "over",
    "know",
    "water",
    "than",
    "call",
    "first",
    "who",
    "may",
    "down",
    "side",
    "been",
    "now",
    "find",
    "any",
    "new",
    "work",
    "part",
    "take",
    "get",
    "place",
    "made",
    "live",
    "where",
    "after",
    "back",
    "little",
    "only",
    "round",
    "man",
    "year",
    "came",
    "show",
    "every",
    "good",
    "me",
    "give",
    "our",
    "under",
    "name",
    "very",
    "through",
    "just",
    "form",
    "sentence",
    "great",
    "think",
    "say",
    "help",
    "low",
    "line",
    "differ",
    "turn",
    "cause",
    "much",
    "mean",
    "before",
    "move",
    "right",
    "boy",
    "old",
    "too",
    "same",
    "tell",
    "does",
    "set",
    "three",
    "want",
    "air",
    "well",
    "also",
    "play",
    "small",
    "end",
    "put",
    "home",
    "read",
    "hand",
    "port",
    "large",
    "spell",
    "add",
    "even",
    "land",
    "here",
    "must",
    "big",
    "high",
    "such",
    "follow",
    "act",
    "why",
    "ask",
    "men",
    "change",
    "went",
    "light",
    "kind",
    "off",
    "need",
    "house",
    "picture",
    "try",
    "us",
    "again",
    "animal",
    "point",
    "mother",
    "world",
    "near",
    "build",
    "self",
    "earth",
    "father",
    "head",
    "stand",
    "own",
    "page",
    "should",
    "country",
    "found",
    "answer",
    "school",
    "grow",
    "study",
    "still",
    "learn",
    "plant",
    "cover",
    "food",
    "sun",
    "four",
    "between",
    "state",
    "keep",
    "eye",
    "never",
    "last",
    "let",
    "thought",
    "city",
    "tree",
    "cross",
    "farm",
    "hard",
    "start",
    "might",
    "story",
    "saw",
    "far",
    "sea",
    "draw",
    "left",
    "late",
    "run",
    "don't",
    "while",
    "press",
    "close",
    "night",
    "real",
    "life",
    "few",
    "north",
    "open",
    "seem",
    "together",
    "next",
    "white",
    "children"
};

#endif // ENCRYPTOR_H_
